# Generated by Django 4.2.10 on 2025-05-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='monthly_revenue',
            field=models.JSONField(default=dict, help_text='Monthly revenue data'),
        ),
    ]
