"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import environ

# Initialize environ
env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='your-secret-key-here')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'core',
    'products',
    'orders',
    'payments',
    'cart',
    'crispy_forms',
    'crispy_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'core.context_processors.categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'
ASGI_APPLICATION = 'ecommerce.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL', default='sqlite:///db.sqlite3')
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Login/Logout URLs
LOGIN_URL = 'core:login'  # Changed from 'account_login'
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'core:home'

# Crispy forms
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development - prints emails to console
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # For production
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'
DEFAULT_FROM_EMAIL = 'ahalo1164@gmail.com'

# Stripe Configuration
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', 'your_stripe_public_key')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'your_stripe_secret_key')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'your_stripe_webhook_secret')

# Payment Settings
PAYMENT_METHODS = {
    'card': {
        'name': 'Credit/Debit Card',
        'icon': 'fa-credit-card',
    },
    'bank': {
        'name': 'Bank Account',
        'icon': 'fa-university',
    },
    'wallet': {
        'name': 'Digital Wallet',
        'icon': 'fa-wallet',
    },
    'upi': {
        'name': 'UPI',
        'icon': 'fa-mobile-alt',
    },
}

# Currency Settings
CURRENCY = 'USD'
CURRENCY_SYMBOL = '₹'  # Indian Rupee symbol

# Redis settings
# REDIS_URL = env('REDIS_URL', default='redis://localhost:6379/0')

# Celery settings
# CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/1')
# CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/2')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Cache settings
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Channel layers for real-time features
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_SSL_REDIRECT = False  # Make sure this is False for development
SECURE_HSTS_SECONDS = 0  # Set to 0 for development
SECURE_HSTS_INCLUDE_SUBDOMAINS = False  # Set to False for development
SECURE_HSTS_PRELOAD = False  # Set to False for development
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF settings
CSRF_COOKIE_SECURE = False  # Changed to False for development
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'  # Changed from None to 'Lax'
CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']
CSRF_USE_SESSIONS = False  # Changed to False to use cookies instead of sessions

# Session settings
SESSION_COOKIE_SECURE = False  # Changed to False for development
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # Changed from None to 'Lax'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds

# CORS settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Remove Django-Axes settings since we're not using it
AXES_FAILURE_LIMIT = None
AXES_LOCK_OUT_AT_FAILURE = None
AXES_COOLOFF_TIME = None
AXES_ENABLED = None
AXES_VERBOSE = None
AXES_META_PRECEDENCE_ORDER = None

# Google reCAPTCHA settings
RECAPTCHA_PUBLIC_KEY = env('RECAPTCHA_PUBLIC_KEY', default='')
RECAPTCHA_PRIVATE_KEY = env('RECAPTCHA_PRIVATE_KEY', default='')

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}

# AWS S3 settings (optional)
if 'AWS_ACCESS_KEY_ID' in env:
    AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME')
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Cart settings
CART_SESSION_ID = 'cart'

# Admin settings
ADMIN_URL = 'admin/'
ADMIN_SITE_HEADER = 'E-commerce Administration'
ADMIN_SITE_TITLE = 'E-commerce Admin Portal'
ADMIN_INDEX_TITLE = 'Welcome to E-commerce Admin Portal'

# Unfold settings
UNFOLD = {
    "SITE_TITLE": "E-commerce Admin",
    "SITE_HEADER": "E-commerce Administration",
    "SITE_SYMBOL": "shopping_cart",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Dashboard",
                "app": "core",
                "icon": "dashboard",
                "items": [
                    {
                        'title': 'Dashboard',
                        "name": "Overview",
                        "link": "/admin/dashboard/",
                        "icon": "dashboard",
                    },
                    {
                        'title': 'Analytics',
                        "name": "Analytics",
                        "link": "/admin/analytics/",
                        "icon": "analytics",
                    }
                ]
            },
            {
                "title": "Products",
                "app": "products",
                "icon": "inventory_2",
                "items": [
                    {
                        'title': 'Products',
                        "name": "Products",
                        "link": "/admin/products/product/",
                        "icon": "inventory_2",
                    },
                    {
                        'title': 'Categories',
                        "name": "Categories",
                        "link": "/admin/products/category/",
                        "icon": "category",
                    },
                    {
                        'title': 'Brands',
                        "name": "Brands",
                        "link": "/admin/products/brand/",
                        "icon": "branding_watermark",
                    }
                ]
            },
            {
                "title": "Orders",
                "app": "orders",
                "icon": "shopping_cart",
                "items": [
                    {
                        "name": "Orders",
                        "link": "/admin/orders/order/",
                        "icon": "shopping_cart",
                    },
                    {
                        "name": "Refunds",
                        "link": "/admin/orders/refund/",
                        "icon": "money_off",
                    }
                ]
            },
            {
                "title": "Customers",
                "app": "auth",
                "icon": "people",
                "items": [
                    {
                        "name": "Users",
                        "link": "/admin/auth/user/",
                        "icon": "person",
                    },
                    {
                        "name": "Groups",
                        "link": "/admin/auth/group/",
                        "icon": "group",
                    }
                ]
            },
            {
                "title": "Settings",
                "app": "core",
                "icon": "settings",
                "items": [
                    {
                        "name": "General",
                        "link": "/admin/core/settings/",
                        "icon": "settings",
                    },
                    {
                        "name": "Payment Methods",
                        "link": "/admin/core/paymentmethod/",
                        "icon": "payment",
                    }
                ]
            }
        ]
    },
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    }
}

# Remove django-allauth settings since we're not using it
SITE_ID = 1
ACCOUNT_AUTHENTICATION_METHOD = None
ACCOUNT_EMAIL_REQUIRED = None
ACCOUNT_EMAIL_VERIFICATION = None
ACCOUNT_USERNAME_REQUIRED = None
ACCOUNT_UNIQUE_EMAIL = None
ACCOUNT_RATE_LIMITS = None
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = None
ACCOUNT_SESSION_REMEMBER = None
ACCOUNT_USERNAME_MIN_LENGTH = None
ACCOUNT_PASSWORD_MIN_LENGTH = None
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = None
ACCOUNT_LOGOUT_ON_GET = None
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = None
ACCOUNT_LOGIN_ON_PASSWORD_RESET = None
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_SUBJECT_PREFIX = None
ACCOUNT_DEFAULT_HTTP_PROTOCOL = None
ACCOUNT_LOGOUT_REDIRECT_URL = None
ACCOUNT_LOGIN_REDIRECT_URL = None
ACCOUNT_EMAIL_CONFIRMATION_URL = None
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = None
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = None
ACCOUNT_EMAIL_CONFIRMATION_COOLDOWN = None
ACCOUNT_EMAIL_CONFIRMATION_HMAC = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_CHANGE = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_ADD = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_REMOVE = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_PRIMARY = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_VERIFIED = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_UNVERIFIED = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_BLACKLIST = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_WHITELIST = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_BLACKLIST = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_WHITELIST = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_REQUIRED = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_BLACKLIST_REQUIRED = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_WHITELIST_REQUIRED = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_OPTIONAL = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_BLACKLIST_OPTIONAL = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_WHITELIST_OPTIONAL = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_DEFAULT = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_BLACKLIST_DEFAULT = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_WHITELIST_DEFAULT = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_CUSTOM = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_BLACKLIST_CUSTOM = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_WHITELIST_CUSTOM = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_REQUIRED_CUSTOM = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_BLACKLIST_REQUIRED_CUSTOM = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_WHITELIST_CUSTOM_REQUIRED = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_CUSTOM_OPTIONAL = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_BLACKLIST_CUSTOM_OPTIONAL = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_WHITELIST_CUSTOM_OPTIONAL = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_CUSTOM_DEFAULT = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_BLACKLIST_CUSTOM_DEFAULT = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_WHITELIST_CUSTOM_DEFAULT = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_CUSTOM_REQUIRED = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_BLACKLIST_CUSTOM_REQUIRED = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_WHITELIST_CUSTOM_REQUIRED = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_CUSTOM_REQUIRED_OPTIONAL = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_BLACKLIST_CUSTOM_REQUIRED_OPTIONAL = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_WHITELIST_CUSTOM_REQUIRED_OPTIONAL = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_CUSTOM_OPTIONAL_DEFAULT = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_BLACKLIST_CUSTOM_OPTIONAL_DEFAULT = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_WHITELIST_CUSTOM_OPTIONAL_DEFAULT = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_CUSTOM_REQUIRED_DEFAULT = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_BLACKLIST_CUSTOM_REQUIRED_DEFAULT = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_WHITELIST_CUSTOM_REQUIRED_DEFAULT = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_CUSTOM_REQUIRED_OPTIONAL_DEFAULT = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_BLACKLIST_CUSTOM_REQUIRED_OPTIONAL_DEFAULT = None
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_DOMAINS_WHITELIST_CUSTOM_REQUIRED_OPTIONAL_DEFAULT = None
